spring.application.name=url-shortener

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=url_shortener
spring.datasource.password=url_shortener
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080

# Logging

logging.level.com.mahdi.url_shortener=DEBUG
spring.output.ansi.enabled=ALWAYS

# Checking Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# Info 
management.info.env.enabled=true

info.app.name=URL Shortener
info.app.description=REST API for creating and managing shortened URLs
info.app.version=1.0.0